server:
  port: 10000
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://49.235.109.10:1412/quasi_world
    username: root
    password: 262342，4191125QW
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true